name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["2.2", "2.3", "2.4", "2.5", "2.6", "2.7"]
        gemfile: ["4.2", "4.2.api", "5.0", "5.1", "5.2"]
        exclude:
          - {ruby-version: "2.7", gemfile: "4.2"}
          - {ruby-version: "2.7", gemfile: "4.2.api"}

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      MYSQL_HOST: 127.0.0.1
      PGHOST: 127.0.0.1
      DB_HOST: 127.0.0.1

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: 1.17.3 # Rails 4.2 requires bundler < 2
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake db:reset test:all

